services:
  frontend:
    build:
      context: .
      args:
        VITE_API_URL: "https://marzetti-peluqueria-backend.326kz3.easypanel.host"
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - marzetti

networks:
  marzetti:
    external: true
    name: marzetti-network
