services:
  frontend:
    build:
      context: .
      args:
        VITE_API_URL: ""
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - marzetti

networks:
  marzetti:
    external: true
    name: marzetti-network
